### ISSUE TITLE
IPv6 port not available. Exiting...

### ISSUE THREAD

**Issue by drunisa007** [drunisa007/tauri_with_react_test#1]
i was using webdriverio to do e2etesting. you can check the conf.js file located at webdriver/webdriverio folder. i did the same steps mentioned in documentation. (https://github.com/chippers/hello_tauri). but i got weird error. i don't quite understand  why ipv6 port is needed. this is the output when we run the wdio.conf.js file.

when we run wdio.conf.js 
this is the output in termial.

```
wdio run wdio.conf.js


Execution of 1 workers started at 2022-11-15T08:06:26.977Z

2022-11-15T08:06:27.026Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-11-15T08:06:27.353Z INFO chromedriver: Initiate Chromedriver Launcher (v8.0.0)
2022-11-15T08:06:27.364Z INFO chromedriver: Start Chromedriver (C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\node_modules\chromedriver\lib\chromedriver\chromedriver.exe) with args --port=9515 --url-base=/
2022-11-15T08:06:27.433Z INFO chromedriver: Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 9515
2022-11-15T08:06:27.434Z INFO chromedriver: Only local connections are allowed.
2022-11-15T08:06:27.435Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-11-15T08:06:27.443Z INFO chromedriver: ChromeDriver was started successfully.
2022-11-15T08:06:27.506Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-11-15T08:06:27.508Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
[0-0] 2022-11-15T08:06:28.393Z INFO @wdio/local-runner: Run worker command: run
[0-0] Starting Microsoft Edge WebDriver 107.0.1418.42 (5ed2a3ace08d6077024f01e03930c3504cbb4e4c) on port 4445
[0-0] To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver
[0-0] 
[0-0] Only local connections are allowed.
[0-0] Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.
[0-0] 
[0-0] RUNNING in chrome - C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\test\specs\example.e2e.js
[0-0] 2022-11-15T08:06:29.084Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-11-15T08:06:29.211Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2022-11-15T08:06:29.212Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       'tauri:options': [Object],
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     'tauri:options': { application: '../../src-tauri/target/debug/my-test-react' },
[0-0]     browserName: 'chrome',
[0-0]     acceptInsecureCerts: true
[0-0]   }
[0-0] }
[0-0] [1668499590.353][SEVERE]: bind() returned an error: Only one usage of each socket address (protocol/network address/port) is normally permitted. (0x2740)
[0-0] IPv6 port not available. Exiting...

DevTools listening on ws://127.0.0.1:50481/devtools/browser/cd60795b-8c9a-43ad-864b-8766d8607e53
[0-0] 2022-11-15T08:06:32.173Z INFO webdriver: COMMAND findElement("link text", "Learn React")
[0-0] 2022-11-15T08:06:32.182Z INFO webdriver: [POST] http://localhost:9515/session/ee20f8199619a271c6b25b72753e4b71/element
[0-0] 2022-11-15T08:06:32.182Z INFO webdriver: DATA { using: 'link text', value: 'Learn React' }
[0-0] 2022-11-15T08:06:32.293Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: 'no such element: Unable to locate element: {"method":"link text","selector":"Learn React"}\n' +
[0-0]     '  (Session info: chrome=107.0.5304.107)',
[0-0]   stacktrace: 'Backtrace:\n' +
[0-0]     '\tOrdinal0 [0x0069ACD3+2075859]\n' +
[0-0]     '\tOrdinal0 [0x0062EE61+1633889]\n' +
[0-0]     '\tOrdinal0 [0x0052B7BD+571325]\n' +
[0-0]     '\tOrdinal0 [0x0055AC2F+764975]\n' +
[0-0]     '\tOrdinal0 [0x0055AE1B+765467]\n' +
[0-0]     '\tOrdinal0 [0x0058D0F2+970994]\n' +
[0-0]     '\tOrdinal0 [0x00577364+881508]\n' +
[0-0]     '\tOrdinal0 [0x0058B56A+963946]\n' +
[0-0]     '\tOrdinal0 [0x00577136+880950]\n' +
[0-0]     '\tOrdinal0 [0x0054FEFD+720637]\n' +
[0-0]     '\tOrdinal0 [0x00550F3F+724799]\n' +
[0-0]     '\tGetHandleVerifier [0x0094EED2+2769538]\n' +
[0-0]     '\tGetHandleVerifier [0x00940D95+2711877]\n' +
[0-0]     '\tGetHandleVerifier [0x0072A03A+521194]\n' +
[0-0]     '\tGetHandleVerifier [0x00728DA0+516432]\n' +
[0-0]     '\tOrdinal0 [0x0063682C+1665068]\n' +
[0-0]     '\tOrdinal0 [0x0063B128+1683752]\n' +
[0-0]     '\tOrdinal0 [0x0063B215+1683989]\n' +
[0-0]     '\tOrdinal0 [0x00646484+1729668]\n' +
[0-0]     '\ttimeGetTime [0x7709B1C8+673880]\n' +
[0-0]     '\ttimeGetTime [0x76FFED9C+33836]\n' +
[0-0]     '\tfltused [0x77AB9290+500876]\n' +
[0-0]     '\tfltused [0x77AB91F8+500724]\n' +
[0-0]     '\tfltused [0x77B770FC+1278712]\n'
[0-0] }
[0-0] 2022-11-15T08:06:32.340Z INFO webdriver: COMMAND findElements("link text", "Learn React")
[0-0] 2022-11-15T08:06:32.342Z INFO webdriver: [POST] http://localhost:9515/session/ee20f8199619a271c6b25b72753e4b71/elements
[0-0] 2022-11-15T08:06:32.344Z INFO webdriver: DATA { using: 'link text', value: 'Learn React' }
[0-0] 2022-11-15T08:06:32.436Z INFO webdriver: RESULT []
[0-0] 2022-11-15T08:06:32.838Z INFO webdriver: COMMAND findElements("link text", "Learn React")
[0-0] 2022-11-15T08:06:32.840Z INFO webdriver: [POST] http://localhost:9515/session/ee20f8199619a271c6b25b72753e4b71/elements
[0-0] 2022-11-15T08:06:32.842Z INFO webdriver: DATA { using: 'link text', value: 'Learn React' }
[0-0] 2022-11-15T08:06:32.888Z INFO webdriver: RESULT []
[0-0] Error in "Hello Tauri.should be tauri dev"
Error: Can't call getText on element with selector "=Learn React" because element wasn't found
    at implicitWait (C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\node_modules\webdriverio\build\utils\implicitWait.js:34:19)
    at Element.elementErrorHandlerCallbackFn (C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\node_modules\webdriverio\build\middlewares.js:20:29)
    at Element.wrapCommandFn (C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\node_modules\@wdio\utils\build\shim.js:137:29)
    at Context.<anonymous> (C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\test\specs\/example.e2e.js:4:19)
[0-0] 2022-11-15T08:06:42.412Z INFO webdriver: RESULT []
[0-0] 2022-11-15T08:06:42.422Z INFO webdriver: COMMAND deleteSession()
[0-0] 2022-11-15T08:06:42.424Z INFO webdriver: [DELETE] http://localhost:9515/session/ee20f8199619a271c6b25b72753e4b71
[0-0] FAILED in chrome - C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\test\specs\example.e2e.js
2022-11-15T08:06:43.094Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-11-15T08:06:43.098Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 107.0.5304.107 windows #0-0] Running: chrome (v107.0.5304.107) on windows
[chrome 107.0.5304.107 windows #0-0] Session ID: ee20f8199619a271c6b25b72753e4b71
[chrome 107.0.5304.107 windows #0-0]
[chrome 107.0.5304.107 windows #0-0] » \test\specs\example.e2e.js
[chrome 107.0.5304.107 windows #0-0] Hello Tauri
[chrome 107.0.5304.107 windows #0-0]    ✖ should be tauri dev
[chrome 107.0.5304.107 windows #0-0]
[chrome 107.0.5304.107 windows #0-0] 1 failing (10.7s)
[chrome 107.0.5304.107 windows #0-0]
[chrome 107.0.5304.107 windows #0-0] 1) Hello Tauri should be tauri dev
[chrome 107.0.5304.107 windows #0-0] Can't call getText on element with selector "=Learn React" because element wasn't found
[chrome 107.0.5304.107 windows #0-0] Error: Can't call getText on element with selector "=Learn React" because element wasn't found
[chrome 107.0.5304.107 windows #0-0]     at implicitWait (C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\node_modules\webdriverio\build\utils\implicitWait.js:34:19)
[chrome 107.0.5304.107 windows #0-0]     at Element.elementErrorHandlerCallbackFn (C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\node_modules\webdriverio\build\middlewares.js:20:29)
[chrome 107.0.5304.107 windows #0-0]     at Element.wrapCommandFn (C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\node_modules\@wdio\utils\build\shim.js:137:29)
[chrome 107.0.5304.107 windows #0-0]     at Context.<anonymous> (C:\Users\drunisa\Documents\react_tauri_my_test\webdriver\webdriverio\test\specs\/example.e2e.js:4:19)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:16
```

**Comment by drunisa007** [comment]
<img width="366" alt="Screen Shot 2022-11-15 at 2 38 57 PM" src="https://user-images.githubusercontent.com/60294099/201864365-99ec6d52-4686-45f7-abeb-0aa4dfe85f3f.png">

**Comment by drunisa007** [comment]
<img width="1440" alt="Screen Shot 2022-11-15 at 2 30 34 PM" src="https://user-images.githubusercontent.com/60294099/201864569-795e0ab3-07f4-4dd4-b3d2-ba3c28325d51.png">
